### ISSUE TITLE
Cannot delete entire phone number due to CC showing as X in the phone number field

### ISSUE THREAD

**Issue by Erin308** [momentum-design/momentum-ui#822] opened 2021-03-17 15:04 UTC
## Issue Type

Component or Pattern Affected:
 Button input on Make a phone call. Shows CC in the textbox

## Expected Behavior
CC should show as X to indicate to the user the phone number entered can be erased 
CC should go away and an X in the phone number text box should show

![Screen Shot 2021-03-17 at 9 41 52 AM](https://user-images.githubusercontent.com/80549034/111486839-d438a380-8705-11eb-9ca3-10b5f6b671ec.png)

## Current Behavior
CC should not display in text box
X should only display to remove a phone number

## Steps to Reproduce (for bugs)

1.Click make a phone call 
2. Enter a valid US number
3. Change the Country code
4. Erase the current US phone number
5. Change the country code back to US
6. Enter a valid US phone number
7. Validation is triggered that the phone number is incorrect
8. Erase the valid US phone number
9. Enter the valid US phone number again

Actual behavior: Valid US phone number with country code +1 will no longer show the parenthesis for the area code and dashes are now missing.

## Context
Remove the CC icon to an X and not trigger validation that the phone number is incorrect 

## Your Environment
Local pointed to the Prod backend
* Icons
* Browser Name and version: Chrome- 89.0.4389.82, Firefox - 86.0.1  Safari - 14.0.3
* Operating System and version: macOS 10.15.7

**Comment by futurethang** [comment] 2021-03-18 16:33
@Erin308 have you discussed the Icon issue with Christopher Philip Coryell? It has to do with version-matching between the respective @momentum-ui libraries in the project's setup, and last time we spoke he figured out how to resolve it.

Basically, this is not a bug with the component per-se, it is a project configuration intricacy based on how Icon fonts and styles are provided to consuming applications.

**Comment by jameswhitely** [comment] 2021-04-07 20:10
Hi @futurethang , Erin has confirmed that this was resolved by correcting versioning.

Thanks.

**Closed** 2021-05-04 16:11 UTC
Labels: @core, @icons, bug
