### ISSUE TITLE
[SearchInput] clear prop causes clear icon and search icon to overlap

### ISSUE THREAD

**Issue by robstax** [momentum-design/momentum-ui#153] opened 2019-03-28 19:53 UTC
## Issue Type
Bug Report

## Component or Pattern Affected
SearchInput

## Expected Behavior
The search_icon and the clear_icon should not overlap in the SearchInput. Don't know if it's quite a "bug" but it's unexpected behavior.

## Current Behavior
If you pass the `clear` prop to SearchInput, the two icons overlap. 

## Possible Solution
1 - Maybe move search_icon the the left when using the clear prop?
There are a number of examples in the collab offerings that use an input with a search icon on the left and a clear icon on the right.
![image](https://user-images.githubusercontent.com/11569788/55188193-025afc80-5158-11e9-8c01-eccb25defe72.png)

![image](https://user-images.githubusercontent.com/11569788/55188229-1868bd00-5158-11e9-98b3-80f131409482.png)
^ this example used `Input` and `Icon` and manual css overrides to get desired behavior

## Steps to Reproduce (for bugs)
https://codesandbox.io/s/r540noq79q
make sure to type in the SearchInput so that the clear icon appears.

## Your Environment

* Library: React, Core, Icons
* Version used: Latest
* Browser Name and version: Chrome and FF
* Operating System and version: macOS

**Comment by bfbiggs** [comment] 2019-07-10 14:58
@robstax The issue is the way in which className is being used.  It should be applied to inputClassName.  That being said, the reason this issue has not been closed is because for future inputs we have decided to add a new InputSection component.

**Comment by pauljeter** [comment] 2019-11-19 20:18
Fixed by #376

**Closed by pauljeter** 2019-11-19 20:18 UTC
Labels: @angular, @core, @react, bug
