### ISSUE TITLE
handle empty string in phone input validation

### ISSUE THREAD

**Issue by ccorCis** [momentum-design/momentum-ui#797] opened 2021-03-02 16:15 UTC
isValid state after blur shows valid when phone input field is empty

## Issue Type
Bug Report

## Component or Pattern Affected
PhoneInput

## Expected Behavior
When the phone input field is blank, the phone input isValid state should be false

## Current Behavior
When I load the phone input component and then blur out of the phone number input box, the component says all input is valid.

## Possible Solution
add logic to the validation that checks for an empty string on change and onblur.

## Steps to Reproduce (for bugs)

1. navigate to a page that utilized <md-phone-input>
2. Click into the phone number input to give it focus, then click on to activate an onBlur. 
3. With an empty string, the input still shows up as valid
4.

## Context

We are using the phone input in a form with a submit button. The form is set to disable the submit button if any form fields are invalid. The form is relying on internal validation performed by PhoneInput, so if the phone input is blank, our form still allows submission of the form with a blank phone number

## Your Environment

* Library: React
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by futurethang** [comment] 2021-03-04 00:29
This is a duplicate of #783

**Comment by futurethang** [comment] 2021-03-05 00:02
Closed by #800

**Closed by futurethang** 2021-03-05 00:02 UTC
Labels: bug, web component
